# Generated by Django 5.2.4 on 2025-08-03 04:25

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=stories.models.story_media_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('expires_at', models.TimeField()),
                ('is_highlighted', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'story_view',
                'verbose_name_plural': 'stories_viewed',
                'db_table': 'stories_viewd',
                'managed': True,
            },
        ),
    ]
